name: tarutas
description: Aplicación de comunicación Bimodal SI-NO.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  flex_color_picker: ^3.4.1

  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_tts: ^3.6.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  riverpod_annotation: ^2.3.4
  path_provider: ^2.1.3
  shared_preferences: ^2.1.0
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.0.2
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/templates/

flutter_native_splash:
  color: "#003A70"
  image: "assets/images/tarutas-iso.png"

  android_12:
    color: "#003A70"
    image: "assets/images/tarutas-iso.png"

  web: false

  android_gravity: center
